const $=id=>document.getElementById(id);
let lastBlob=null,lastName='app.apk',iconData='';
function toggleSide(){$('side').classList.toggle('open')}
function page(id,btn){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('title').textContent=btn.textContent.trim();$('sub').textContent=id==='engine'?'Build environment and architecture':'Build Android WebView applications from a website URL';if(id==='history')renderHistory();updateStats();if(innerWidth<901)$('side').classList.remove('open')}
function makeFrame(id,u,fullscreen=false){let f=$(id);if(!u){f.innerHTML='<div class="empty"><div><strong>Preview</strong>Masukkan URL HTTPS untuk memuat preview.</div></div>';return}try{let x=new URL(u);if(!['http:','https:'].includes(x.protocol))throw 0;f.innerHTML='<div class="device"><div class="phone '+(fullscreen?'fullscreen':'')+'"><div class="phonebar"><span>9:41</span><span>WebView</span></div><iframe src="'+x.href.replace(/"/g,'&quot;')+'" referrerpolicy="no-referrer"></iframe></div></div>'}catch{f.innerHTML='<div class="empty"><div><strong>URL tidak valid</strong>Gunakan contoh https://example.com</div></div>'}}
function preview(){let u=$('url').value.trim();makeFrame('frame',u,$('fullscreen')?.checked);if($('previewState'))$('previewState').textContent=u?'LOADED':'WAITING'}
function syncBuilder(){let u=$('burl').value.trim();makeFrame('bframe',u,$('bfullscreen')?.checked)}
function updatePreviewMode(){let u=$('burl')?.value.trim();if($('fullscreenText'))$('fullscreenText').textContent=$('bfullscreen').checked?'ON':'OFF';if($('previewVersion'))$('previewVersion').textContent='Version '+($('bversion').value.trim()||'1.0');makeFrame('bframe',u,$('bfullscreen').checked);preview()}
function setPreviewTab(tab){document.querySelectorAll('.previewtabs button').forEach(x=>x.classList.remove('active'));$(tab==='web'?'tabWeb':'tabApk').classList.add('active');let u=$('burl').value.trim();if(tab==='web'){makeFrame('bframe',u,false)}else{makeFrame('bframe',u,$('bfullscreen').checked)}}
function valid(u){try{let x=new URL(u);return ['http:','https:'].includes(x.protocol)}catch{return false}}
function versionValid(v){return /^\d+(\.\d+){0,3}$/.test(String(v||'').trim())}
async function build(){let u=$('url').value.trim(),n=$('name').value.trim(),p=$('pkg').value.trim(),v=$('version').value.trim()||'1.0';if(!valid(u)||!n||!versionValid(v)){alert('Masukkan URL, nama aplikasi, dan versi yang valid.');return}await doBuild({url:u,name:n,pkg:p,version:v,fullscreen:$('fullscreen').checked,icon:iconData})}
async function buildFromBuilder(){let u=$('burl').value.trim(),n=$('bname').value.trim(),p=$('bpkg').value.trim(),v=$('bversion').value.trim()||'1.0';if(!valid(u)||!n||!versionValid(v)){alert('Masukkan URL, nama aplikasi, dan versi yang valid.');return}await doBuild({url:u,name:n,pkg:p,version:v,fullscreen:$('bfullscreen').checked,icon:iconData})}
function handleIcon(e){let file=e.target.files?.[0];if(!file)return;if(file.type!=='image/png'){alert('Icon harus PNG.');e.target.value='';return}if(file.size>2*1024*1024){alert('Ukuran icon maksimal 2 MB.');e.target.value='';return}let r=new FileReader();r.onload=()=>{iconData=r.result;$('iconName').textContent=file.name+' • '+Math.round(file.size/1024)+' KB';$('iconPreview').innerHTML='<img src="'+iconData+'" alt="icon">'};r.readAsDataURL(file)}
async function doBuild(data){$('modal').classList.add('show');$('download').classList.remove('show');setProgress(8,'Validating configuration...');try{setProgress(18,'Preparing WebView configuration...');setProgress(25,'Sending build request...');let r=await fetch('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok){let t=await r.text();throw new Error(t||'Build failed')}setProgress(70,'Receiving APK...');let blob=await r.blob();if(blob.size<1000)throw new Error('APK response is too small');lastBlob=blob;lastName=safe(data.name)+'-v'+safe(data.version||'1.0')+'.apk';setProgress(100,'Build complete');$('download').classList.add('show');saveHistory({name:data.name,url:data.url,pkg:data.pkg,version:data.version,fullscreen:data.fullscreen,status:'Success',date:new Date().toLocaleString('id-ID')})}catch(e){setProgress(100,'Build failed: '+e.message);saveHistory({name:data.name,url:data.url,pkg:data.pkg,version:data.version,fullscreen:data.fullscreen,status:'Failed',date:new Date().toLocaleString('id-ID')})}}
function setProgress(n,t){$('mbar').style.width=n+'%';$('mstatus').textContent=n+'% — '+t}
function closeModal(){$('modal').classList.remove('show')}
function downloadLast(){if(!lastBlob)return;let a=document.createElement('a');a.href=URL.createObjectURL(lastBlob);a.download=lastName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function safe(s){return String(s).replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,40)||'app'}
function getHistory(){return JSON.parse(localStorage.getItem('wta-history')||'[]')}
function saveHistory(x){let h=getHistory();h.unshift(x);localStorage.setItem('wta-history',JSON.stringify(h.slice(0,50)));updateStats();renderHistory()}
function renderHistory(){let h=getHistory();$('historyBody').innerHTML=h.length?h.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.url)+'</td><td>'+esc(x.date)+'</td><td><span class="status">'+esc(x.status)+(x.version?' • v'+esc(x.version):'')+'</span></td></tr>').join(''):'<tr><td colspan="4" class="emptyrow">Belum ada build.</td></tr>'}
function clearHistory(){localStorage.removeItem('wta-history');renderHistory();updateStats()}
function updateStats(){let h=getHistory();$('sTotal').textContent=h.length;$('sSuccess').textContent=h.filter(x=>x.status==='Success').length;$('sFailed').textContent=h.filter(x=>x.status==='Failed').length}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
updateStats();renderHistory();
